### ISSUE TITLE
About realization

### ISSUE THREAD

**Issue by syan1992** [addisonElliott/polarTransform#4]
Hi, 
I'd like to know if the realization similar to Matlab. I find the result seems different from matlab.
Thanks a lot.

**Comment by addisonElliott** [comment]
Not entirely sure. I did not compare this library's results with MATLAB.

Can you give an isolated example in MATLAB & Python that produces different results?

**Comment by syan1992** [comment]
![default](https://user-images.githubusercontent.com/17903726/43242738-5bef9718-90d5-11e8-97cf-b54122fc8801.PNG)

**Comment by syan1992** [comment]
I subtract the result of matlab and python, I feel the difference of the boundary is large. I'm not sure if it related to the realization.

**Comment by addisonElliott** [comment]
Oh okay, I see what you are saying now. Attaining pixel-perfect polar transformations between MATLAB & Python will be difficult because the underlying methods used may be a bit different. Here are some reasons why:
* The interpolation may be different, polarTransform defaults to bicubic. Not sure why MATLAB uses by default.
* Increased accuracy due to Python using 64-bit floating point. Once again, not sure how many bits is used for floating point calculation. This is probably a small different.
* Resolution of the polar image (polarImageSize). A difference in MATLAB/Python for resolution will cause a difference in the images.

Do the two images produced between MATLAB & polarTransform look similar? If so, that may be sufficient for your purposes. I did my best to validate the library to ensure that the polar transform was done correctly.

If you want to investigate further, please write a test case (MATLAB & polarTransform code) with example images that clearly shows the difference in images.

The steps for tracking this down would be to have a test case in Python & MATLAB that produces different results. Then pick one of the large pixel differences and do the math by hand to see which implementation is doing it correctly.

**Comment by syan1992** [comment]
I got it. Thanks for ur detailed answer.
